const data = {
  products: [
    {
      name: 'Butterfly long ballerina nails',
      slug: 'Butterfly-long-ballerina-press-on-nails',
      category: 'Long Nails',
      image: '/images/1.png',
      price: 10,
      brand: 'Nails Republic',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Butterfly long ballerina acrylic press on nails',
    },
    {
      name: 'Butterfly long ballerina nails',
      slug: 'Butterfly-ballerina-press-on-nails',
      category: 'Press On Nails',
      image: '/images/2.png',
      price: 10,
      brand: 'Nails Republic',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Butterfly long ballerina acrylic press on nails',
    },
    {
      name: 'Butterfly long ballerina nails',
      slug: 'Butterfly-press-on-nails',
      category: 'Long',
      image: '/images/3.png',
      price: 10,
      brand: 'Nails Republic',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Butterfly long ballerina acrylic press on nails',
    },
    {
      name: 'Butterfly long ballerina nails',
      slug: 'press-on-nails',
      category: 'On Nails',
      image: '/images/4.png',
      price: 10,
      brand: 'Nails Republic',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Butterfly long ballerina acrylic press on nails',
    },
  ],
};

export default data;
